In [1]:
import numpy as np

In [4]:
rec = np.array([[1, 2], [4, 5], [7, 8]])

In [5]:
rec

array([[1, 2],
       [4, 5],
       [7, 8]])

In [12]:
# np.where(rec == (2, 2)).all(axis=1)
np.where((rec == (1, 2)).all(axis=1))[0]

array([0])

In [13]:
pgv = np.array([5, 3, 10])
indices = np.array([2, 0, 1])

In [16]:
pgv[indices.argsort()]

array([ 3, 10,  5])